#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP

dns_conf () {
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_conf "$1" "www"
  dns_conf "$1" "100.26.169.102"
  dns_conf "$1" "100.26.174.69"
  dns_conf "$1" "18.207.141.110"
elif [ "$#" == 2 ]
then
  dns_conf "$1" "$2"
fi
