#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello WOrld!" | tee /var/www/html/index.html
service nginx restart
