#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
cat << _EOF_ > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

	add_header X-served-By $HOSTNAME;

	location /redirect_me {
		return 301 https://github.com/1CyBeR-J1;
	}
}
_EOF_
sudo service nginx restart
