#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
Hour=0
i=1
while [ $Hour -lt 13 ]
do
	echo "Hour: $Hour"
		while [ $i -le 59 ]
		do
			echo "$i"
			i=$((++1))
		done
	Hour=$((Hour++))
done
