#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first - display
for file in *
do
	echo "${file#*-}"
done
